### PR TITLE
release: upgrade version 0.3.0

### PR DESCRIPTION
**Pull request by dominikhorn93**
**Issue**

**Description**

**Checklist**

* Code is easy to understand
* No obvious errors or bugs
* CI/CD Pipelines did run successfully
* Tests were implemented
* Documentation was created

### CODE REVIEW

**Review by DaAnda97 — APPROVED** [review]

**Comment by dominikhorn93** [comment]
@DaAnda97  @Hafflgav  in this PR one of you could add the 0.2.0 to the docs.

**Review by Hafflgav — CHANGES_REQUESTED** [review]
Todo before merge: 
- [ ] Update Readme
- [ ] Update Docs (miranum.com) 
- [ ] Create follow up task to update dependency in miranum-consulting

**Comment by Hafflgav** [comment]
FYI: I will update the docs tomorrow morning or later today. 👋

**Comment by Hafflgav** [comment]
When releasing a new version (besides of a snapshot) we should include changes which have happened similar to such a pattern: 

> <Version>
> 
> ⭐ New Features
> ...
> 
> 🐞 Bug Fixes
> ...
> 
> 🛑  Breaking Changes
> ... 

What do you think about this?

**Pull request merged**
